// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVmnTOSTmftJ8hh2_D5k9eZpixn0gZjxU',
    appId: '1:1001716936721:web:274869d5acda380bdf41b0',
    messagingSenderId: '1001716936721',
    projectId: 'cargadatos-5e348',
    authDomain: 'cargadatos-5e348.firebaseapp.com',
    storageBucket: 'cargadatos-5e348.firebasestorage.app',
    measurementId: 'G-NWVET7HF6Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-WVM8WGVOA65MTz_hJKz_1KpK-K5I7sQ',
    appId: '1:1001716936721:android:4cdc5ff6452f83f6df41b0',
    messagingSenderId: '1001716936721',
    projectId: 'cargadatos-5e348',
    storageBucket: 'cargadatos-5e348.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUpGE-5evfgavGJyxdDpGEPVkKg1lfcdg',
    appId: '1:1001716936721:ios:c8f80bd7e3bdd0d1df41b0',
    messagingSenderId: '1001716936721',
    projectId: 'cargadatos-5e348',
    storageBucket: 'cargadatos-5e348.firebasestorage.app',
    iosBundleId: 'com.example.cargaDatos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUpGE-5evfgavGJyxdDpGEPVkKg1lfcdg',
    appId: '1:1001716936721:ios:c8f80bd7e3bdd0d1df41b0',
    messagingSenderId: '1001716936721',
    projectId: 'cargadatos-5e348',
    storageBucket: 'cargadatos-5e348.firebasestorage.app',
    iosBundleId: 'com.example.cargaDatos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVmnTOSTmftJ8hh2_D5k9eZpixn0gZjxU',
    appId: '1:1001716936721:web:2804cc8121d0972edf41b0',
    messagingSenderId: '1001716936721',
    projectId: 'cargadatos-5e348',
    authDomain: 'cargadatos-5e348.firebaseapp.com',
    storageBucket: 'cargadatos-5e348.firebasestorage.app',
    measurementId: 'G-JEY4FE95RT',
  );
}
